# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proy2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 721)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pestanas = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pestanas.sizePolicy().hasHeightForWidth())
        self.pestanas.setSizePolicy(sizePolicy)
        self.pestanas.setObjectName("pestanas")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.expRegular1Txt = QtWidgets.QLineEdit(self.tab_2)
        self.expRegular1Txt.setObjectName("expRegular1Txt")
        self.gridLayout_4.addWidget(self.expRegular1Txt, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 2, 1, 1)
        self.ok1Btn = QtWidgets.QPushButton(self.tab_2)
        self.ok1Btn.setObjectName("ok1Btn")
        self.gridLayout_4.addWidget(self.ok1Btn, 2, 3, 1, 1)
        self.campoTexto1 = QtWidgets.QTextEdit(self.tab_2)
        self.campoTexto1.setObjectName("campoTexto1")
        self.gridLayout_4.addWidget(self.campoTexto1, 1, 0, 3, 2)
        self.pestanas.addTab(self.tab_2, "")
        self.diagramaTab = QtWidgets.QWidget()
        self.diagramaTab.setObjectName("diagramaTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.diagramaTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.estInicialLbl = QtWidgets.QLabel(self.diagramaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estInicialLbl.sizePolicy().hasHeightForWidth())
        self.estInicialLbl.setSizePolicy(sizePolicy)
        self.estInicialLbl.setObjectName("estInicialLbl")
        self.gridLayout_2.addWidget(self.estInicialLbl, 4, 11, 1, 1)
        self.alfabetoLbl = QtWidgets.QLabel(self.diagramaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alfabetoLbl.sizePolicy().hasHeightForWidth())
        self.alfabetoLbl.setSizePolicy(sizePolicy)
        self.alfabetoLbl.setObjectName("alfabetoLbl")
        self.gridLayout_2.addWidget(self.alfabetoLbl, 3, 11, 1, 1)
        self.estInicial2Txt = QtWidgets.QLineEdit(self.diagramaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estInicial2Txt.sizePolicy().hasHeightForWidth())
        self.estInicial2Txt.setSizePolicy(sizePolicy)
        self.estInicial2Txt.setObjectName("estInicial2Txt")
        self.gridLayout_2.addWidget(self.estInicial2Txt, 4, 12, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.diagramaTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 11, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.diagramaTab)
        self.label_4.setMinimumSize(QtCore.QSize(110, 29))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 22, 0, 1, 1)
        self.checkBoxDerecha2 = QtWidgets.QCheckBox(self.diagramaTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.checkBoxDerecha2.setFont(font)
        self.checkBoxDerecha2.setObjectName("checkBoxDerecha2")
        self.gridLayout_2.addWidget(self.checkBoxDerecha2, 18, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.diagramaTab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 24, 8, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.diagramaTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 24, 0, 1, 1)
        self.alfabeto2Txt = QtWidgets.QLineEdit(self.diagramaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alfabeto2Txt.sizePolicy().hasHeightForWidth())
        self.alfabeto2Txt.setSizePolicy(sizePolicy)
        self.alfabeto2Txt.setObjectName("alfabeto2Txt")
        self.gridLayout_2.addWidget(self.alfabeto2Txt, 3, 12, 1, 1)
        self.aplicar2Btn = QtWidgets.QPushButton(self.diagramaTab)
        self.aplicar2Btn.setObjectName("aplicar2Btn")
        self.gridLayout_2.addWidget(self.aplicar2Btn, 6, 12, 1, 1)
        self.estAceptadoresLbl = QtWidgets.QLabel(self.diagramaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estAceptadoresLbl.sizePolicy().hasHeightForWidth())
        self.estAceptadoresLbl.setSizePolicy(sizePolicy)
        self.estAceptadoresLbl.setObjectName("estAceptadoresLbl")
        self.gridLayout_2.addWidget(self.estAceptadoresLbl, 5, 11, 1, 1)
        self.estAceptadores2Txt = QtWidgets.QLineEdit(self.diagramaTab)
        self.estAceptadores2Txt.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estAceptadores2Txt.sizePolicy().hasHeightForWidth())
        self.estAceptadores2Txt.setSizePolicy(sizePolicy)
        self.estAceptadores2Txt.setObjectName("estAceptadores2Txt")
        self.gridLayout_2.addWidget(self.estAceptadores2Txt, 5, 12, 1, 1)
        self.label = QtWidgets.QLabel(self.diagramaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 7, 11, 1, 1)
        self.origenLbl = QtWidgets.QLabel(self.diagramaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.origenLbl.sizePolicy().hasHeightForWidth())
        self.origenLbl.setSizePolicy(sizePolicy)
        self.origenLbl.setObjectName("origenLbl")
        self.gridLayout_2.addWidget(self.origenLbl, 8, 11, 1, 1)
        self.destinoLbl = QtWidgets.QLabel(self.diagramaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destinoLbl.sizePolicy().hasHeightForWidth())
        self.destinoLbl.setSizePolicy(sizePolicy)
        self.destinoLbl.setObjectName("destinoLbl")
        self.gridLayout_2.addWidget(self.destinoLbl, 9, 11, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.diagramaTab)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 24, 3, 1, 1)
        self.origen2Txt_4 = QtWidgets.QLineEdit(self.diagramaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.origen2Txt_4.sizePolicy().hasHeightForWidth())
        self.origen2Txt_4.setSizePolicy(sizePolicy)
        self.origen2Txt_4.setObjectName("origen2Txt_4")
        self.gridLayout_2.addWidget(self.origen2Txt_4, 8, 12, 1, 1)
        self.destino2Txt_2 = QtWidgets.QLineEdit(self.diagramaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destino2Txt_2.sizePolicy().hasHeightForWidth())
        self.destino2Txt_2.setSizePolicy(sizePolicy)
        self.destino2Txt_2.setObjectName("destino2Txt_2")
        self.gridLayout_2.addWidget(self.destino2Txt_2, 9, 12, 1, 1)
        self.guardarAut2 = QtWidgets.QPushButton(self.diagramaTab)
        self.guardarAut2.setObjectName("guardarAut2")
        self.gridLayout_2.addWidget(self.guardarAut2, 13, 12, 1, 1)
        self.valorLbl = QtWidgets.QLabel(self.diagramaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valorLbl.sizePolicy().hasHeightForWidth())
        self.valorLbl.setSizePolicy(sizePolicy)
        self.valorLbl.setObjectName("valorLbl")
        self.gridLayout_2.addWidget(self.valorLbl, 10, 11, 1, 1)
        self.valor2Txt = QtWidgets.QLineEdit(self.diagramaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valor2Txt.sizePolicy().hasHeightForWidth())
        self.valor2Txt.setSizePolicy(sizePolicy)
        self.valor2Txt.setObjectName("valor2Txt")
        self.gridLayout_2.addWidget(self.valor2Txt, 10, 12, 1, 1)
        self.aplicarTransiBtn = QtWidgets.QPushButton(self.diagramaTab)
        self.aplicarTransiBtn.setObjectName("aplicarTransiBtn")
        self.gridLayout_2.addWidget(self.aplicarTransiBtn, 11, 12, 1, 1)
        self.guardar_gram2 = QtWidgets.QPushButton(self.diagramaTab)
        self.guardar_gram2.setObjectName("guardar_gram2")
        self.gridLayout_2.addWidget(self.guardar_gram2, 14, 12, 1, 1)
        self.checkBoxIzquierda2 = QtWidgets.QCheckBox(self.diagramaTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.checkBoxIzquierda2.setFont(font)
        self.checkBoxIzquierda2.setObjectName("checkBoxIzquierda2")
        self.gridLayout_2.addWidget(self.checkBoxIzquierda2, 18, 11, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.diagramaTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 16, 0, 1, 8)
        self.label_24 = QtWidgets.QLabel(self.diagramaTab)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 24, 12, 1, 1)
        self.comboBoxProducc2 = QtWidgets.QComboBox(self.diagramaTab)
        self.comboBoxProducc2.setObjectName("comboBoxProducc2")
        self.gridLayout_2.addWidget(self.comboBoxProducc2, 24, 11, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.diagramaTab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 22, 8, 1, 1)
        self.vInicialTxt = QtWidgets.QLineEdit(self.diagramaTab)
        self.vInicialTxt.setObjectName("vInicialTxt")
        self.gridLayout_2.addWidget(self.vInicialTxt, 22, 11, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.diagramaTab)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 22, 3, 1, 1)
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.diagramaTab)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.gridLayout_2.addWidget(self.graphicsView_4, 2, 0, 14, 9)
        self.combovariables2 = QtWidgets.QComboBox(self.diagramaTab)
        self.combovariables2.setObjectName("combovariables2")
        self.gridLayout_2.addWidget(self.combovariables2, 22, 1, 1, 2)
        self.comboBoxTermin2 = QtWidgets.QComboBox(self.diagramaTab)
        self.comboBoxTermin2.setObjectName("comboBoxTermin2")
        self.gridLayout_2.addWidget(self.comboBoxTermin2, 24, 1, 1, 2)
        self.limpiar2_1Btn = QtWidgets.QPushButton(self.diagramaTab)
        self.limpiar2_1Btn.setObjectName("limpiar2_1Btn")
        self.gridLayout_2.addWidget(self.limpiar2_1Btn, 15, 12, 1, 1)
        self.limpiar2_2Btn = QtWidgets.QPushButton(self.diagramaTab)
        self.limpiar2_2Btn.setObjectName("limpiar2_2Btn")
        self.gridLayout_2.addWidget(self.limpiar2_2Btn, 23, 12, 1, 1)
        self.pestanas.addTab(self.diagramaTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_15 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 2, 3, 1, 1)
        self.guardar_gram3Btn = QtWidgets.QPushButton(self.tab)
        self.guardar_gram3Btn.setObjectName("guardar_gram3Btn")
        self.gridLayout_10.addWidget(self.guardar_gram3Btn, 5, 4, 1, 1)
        self.variables3Txt = QtWidgets.QLineEdit(self.tab)
        self.variables3Txt.setObjectName("variables3Txt")
        self.gridLayout_10.addWidget(self.variables3Txt, 2, 1, 1, 1)
        self.ok3_1Btn = QtWidgets.QPushButton(self.tab)
        self.ok3_1Btn.setObjectName("ok3_1Btn")
        self.gridLayout_10.addWidget(self.ok3_1Btn, 2, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 4, 0, 1, 1)
        self.vInicial3Txt = QtWidgets.QLineEdit(self.tab)
        self.vInicial3Txt.setObjectName("vInicial3Txt")
        self.gridLayout_10.addWidget(self.vInicial3Txt, 4, 1, 1, 1)
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.gridLayout_10.addWidget(self.graphicsView_3, 11, 0, 1, 7)
        self.ok3_3Btn = QtWidgets.QPushButton(self.tab)
        self.ok3_3Btn.setObjectName("ok3_3Btn")
        self.gridLayout_10.addWidget(self.ok3_3Btn, 4, 4, 1, 1)
        self.ok3_2Btn = QtWidgets.QPushButton(self.tab)
        self.ok3_2Btn.setObjectName("ok3_2Btn")
        self.gridLayout_10.addWidget(self.ok3_2Btn, 2, 9, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 2, 5, 1, 1)
        self.terminales3Txt = QtWidgets.QLineEdit(self.tab)
        self.terminales3Txt.setObjectName("terminales3Txt")
        self.gridLayout_10.addWidget(self.terminales3Txt, 2, 6, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_10.addWidget(self.label_17, 2, 7, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 4, 5, 1, 1)
        self.comboBoxProducc3 = QtWidgets.QComboBox(self.tab)
        self.comboBoxProducc3.setObjectName("comboBoxProducc3")
        self.gridLayout_10.addWidget(self.comboBoxProducc3, 4, 6, 1, 1)
        self.agregarProd3Btn = QtWidgets.QPushButton(self.tab)
        self.agregarProd3Btn.setObjectName("agregarProd3Btn")
        self.gridLayout_10.addWidget(self.agregarProd3Btn, 4, 9, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 4, 7, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_10.addWidget(self.label_20, 7, 0, 1, 1)
        self.cadena3Txt = QtWidgets.QLineEdit(self.tab)
        self.cadena3Txt.setObjectName("cadena3Txt")
        self.gridLayout_10.addWidget(self.cadena3Txt, 7, 1, 1, 1)
        self.checkBoxDerecha3 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.checkBoxDerecha3.setFont(font)
        self.checkBoxDerecha3.setObjectName("checkBoxDerecha3")
        self.gridLayout_10.addWidget(self.checkBoxDerecha3, 7, 9, 1, 1)
        self.generar3Btn = QtWidgets.QPushButton(self.tab)
        self.generar3Btn.setObjectName("generar3Btn")
        self.gridLayout_10.addWidget(self.generar3Btn, 11, 9, 1, 1)
        self.checkBoxIzquierda3 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.checkBoxIzquierda3.setFont(font)
        self.checkBoxIzquierda3.setObjectName("checkBoxIzquierda3")
        self.gridLayout_10.addWidget(self.checkBoxIzquierda3, 10, 9, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_10.addWidget(self.label_21, 6, 9, 1, 1)
        self.limpiar3_1Btn = QtWidgets.QPushButton(self.tab)
        self.limpiar3_1Btn.setObjectName("limpiar3_1Btn")
        self.gridLayout_10.addWidget(self.limpiar3_1Btn, 6, 4, 1, 1)
        self.limpiar3_2Btn = QtWidgets.QPushButton(self.tab)
        self.limpiar3_2Btn.setObjectName("limpiar3_2Btn")
        self.gridLayout_10.addWidget(self.limpiar3_2Btn, 12, 9, 1, 1)
        self.pestanas.addTab(self.tab, "")
        self.maneraFTab = QtWidgets.QWidget()
        self.maneraFTab.setObjectName("maneraFTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.maneraFTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.maneraFTab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.maquinaLbl = QtWidgets.QLabel(self.frame)
        self.maquinaLbl.setGeometry(QtCore.QRect(0, 180, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.maquinaLbl.setFont(font)
        self.maquinaLbl.setObjectName("maquinaLbl")
        self.cBoxEstados4 = QtWidgets.QComboBox(self.frame)
        self.cBoxEstados4.setGeometry(QtCore.QRect(50, 190, 91, 21))
        self.cBoxEstados4.setObjectName("cBoxEstados4")
        self.cBoxEstInicial4 = QtWidgets.QComboBox(self.frame)
        self.cBoxEstInicial4.setGeometry(QtCore.QRect(380, 190, 101, 21))
        self.cBoxEstInicial4.setObjectName("cBoxEstInicial4")
        self.cBoxTransiciones4_ = QtWidgets.QComboBox(self.frame)
        self.cBoxTransiciones4_.setGeometry(QtCore.QRect(240, 190, 131, 21))
        self.cBoxTransiciones4_.setObjectName("cBoxTransiciones4_")
        self.cBoxAlfabeto4_ = QtWidgets.QComboBox(self.frame)
        self.cBoxAlfabeto4_.setGeometry(QtCore.QRect(150, 190, 81, 21))
        self.cBoxAlfabeto4_.setObjectName("cBoxAlfabeto4_")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(830, 180, 16, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.QLbl = QtWidgets.QLabel(self.frame)
        self.QLbl.setGeometry(QtCore.QRect(90, 160, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.QLbl.setFont(font)
        self.QLbl.setObjectName("QLbl")
        self.inicial2Lbl = QtWidgets.QLabel(self.frame)
        self.inicial2Lbl.setGeometry(QtCore.QRect(410, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.inicial2Lbl.setFont(font)
        self.inicial2Lbl.setObjectName("inicial2Lbl")
        self.aceptadores2Lbl = QtWidgets.QLabel(self.frame)
        self.aceptadores2Lbl.setGeometry(QtCore.QRect(520, 170, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.aceptadores2Lbl.setFont(font)
        self.aceptadores2Lbl.setObjectName("aceptadores2Lbl")
        self.alfabeto2Lbl = QtWidgets.QLabel(self.frame)
        self.alfabeto2Lbl.setGeometry(QtCore.QRect(180, 160, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.alfabeto2Lbl.setFont(font)
        self.alfabeto2Lbl.setObjectName("alfabeto2Lbl")
        self.transiLbl = QtWidgets.QLabel(self.frame)
        self.transiLbl.setGeometry(QtCore.QRect(300, 160, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.transiLbl.setFont(font)
        self.transiLbl.setObjectName("transiLbl")
        self.checkBoxInicial4 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxInicial4.setGeometry(QtCore.QRect(10, 50, 98, 21))
        self.checkBoxInicial4.setObjectName("checkBoxInicial4")
        self.checkBoxAceptador4 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxAceptador4.setGeometry(QtCore.QRect(120, 50, 98, 21))
        self.checkBoxAceptador4.setObjectName("checkBoxAceptador4")
        self.anadirEstado4Btn = QtWidgets.QPushButton(self.frame)
        self.anadirEstado4Btn.setGeometry(QtCore.QRect(260, 50, 111, 29))
        self.anadirEstado4Btn.setObjectName("anadirEstado4Btn")
        self.origen4Txt = QtWidgets.QTextEdit(self.frame)
        self.origen4Txt.setGeometry(QtCore.QRect(10, 130, 71, 21))
        self.origen4Txt.setObjectName("origen4Txt")
        self.origenLbl_2 = QtWidgets.QLabel(self.frame)
        self.origenLbl_2.setGeometry(QtCore.QRect(20, 100, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.origenLbl_2.setFont(font)
        self.origenLbl_2.setObjectName("origenLbl_2")
        self.transi4Btn = QtWidgets.QPushButton(self.frame)
        self.transi4Btn.setGeometry(QtCore.QRect(580, 120, 141, 29))
        self.transi4Btn.setObjectName("transi4Btn")
        self.alfabeto2Lbl_2 = QtWidgets.QLabel(self.frame)
        self.alfabeto2Lbl_2.setGeometry(QtCore.QRect(10, 0, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.alfabeto2Lbl_2.setFont(font)
        self.alfabeto2Lbl_2.setObjectName("alfabeto2Lbl_2")
        self.alfabeto4 = QtWidgets.QLineEdit(self.frame)
        self.alfabeto4.setGeometry(QtCore.QRect(50, 10, 181, 21))
        self.alfabeto4.setObjectName("alfabeto4")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(240, 10, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.alfabeto2Lbl_3 = QtWidgets.QLabel(self.frame)
        self.alfabeto2Lbl_3.setGeometry(QtCore.QRect(430, 0, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.alfabeto2Lbl_3.setFont(font)
        self.alfabeto2Lbl_3.setObjectName("alfabeto2Lbl_3")
        self.alfabetoPila4 = QtWidgets.QLineEdit(self.frame)
        self.alfabetoPila4.setGeometry(QtCore.QRect(470, 10, 181, 21))
        self.alfabetoPila4.setObjectName("alfabetoPila4")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(650, 10, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.agregarAlfabeto4 = QtWidgets.QPushButton(self.frame)
        self.agregarAlfabeto4.setGeometry(QtCore.QRect(260, 0, 121, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.agregarAlfabeto4.setFont(font)
        self.agregarAlfabeto4.setObjectName("agregarAlfabeto4")
        self.agregarAPila4 = QtWidgets.QPushButton(self.frame)
        self.agregarAPila4.setGeometry(QtCore.QRect(670, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.agregarAPila4.setFont(font)
        self.agregarAPila4.setObjectName("agregarAPila4")
        self.sEntrada4Txt = QtWidgets.QTextEdit(self.frame)
        self.sEntrada4Txt.setGeometry(QtCore.QRect(110, 130, 91, 21))
        self.sEntrada4Txt.setObjectName("sEntrada4Txt")
        self.origenLbl_3 = QtWidgets.QLabel(self.frame)
        self.origenLbl_3.setGeometry(QtCore.QRect(180, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.origenLbl_3.setFont(font)
        self.origenLbl_3.setObjectName("origenLbl_3")
        self.origenLbl_4 = QtWidgets.QLabel(self.frame)
        self.origenLbl_4.setGeometry(QtCore.QRect(100, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.origenLbl_4.setFont(font)
        self.origenLbl_4.setObjectName("origenLbl_4")
        self.sPila4Txt = QtWidgets.QTextEdit(self.frame)
        self.sPila4Txt.setGeometry(QtCore.QRect(210, 130, 91, 21))
        self.sPila4Txt.setObjectName("sPila4Txt")
        self.origenLbl_5 = QtWidgets.QLabel(self.frame)
        self.origenLbl_5.setGeometry(QtCore.QRect(220, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.origenLbl_5.setFont(font)
        self.origenLbl_5.setObjectName("origenLbl_5")
        self.destino4Txt = QtWidgets.QTextEdit(self.frame)
        self.destino4Txt.setGeometry(QtCore.QRect(330, 130, 91, 21))
        self.destino4Txt.setObjectName("destino4Txt")
        self.origenLbl_6 = QtWidgets.QLabel(self.frame)
        self.origenLbl_6.setGeometry(QtCore.QRect(350, 100, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.origenLbl_6.setFont(font)
        self.origenLbl_6.setObjectName("origenLbl_6")
        self.simboloEscribirP4Txt = QtWidgets.QTextEdit(self.frame)
        self.simboloEscribirP4Txt.setGeometry(QtCore.QRect(450, 130, 91, 21))
        self.simboloEscribirP4Txt.setObjectName("simboloEscribirP4Txt")
        self.origenLbl_7 = QtWidgets.QLabel(self.frame)
        self.origenLbl_7.setGeometry(QtCore.QRect(420, 100, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.origenLbl_7.setFont(font)
        self.origenLbl_7.setObjectName("origenLbl_7")
        self.cBoxAceptadores4 = QtWidgets.QComboBox(self.frame)
        self.cBoxAceptadores4.setGeometry(QtCore.QRect(490, 190, 101, 21))
        self.cBoxAceptadores4.setObjectName("cBoxAceptadores4")
        self.cBoxSimbolosPila4 = QtWidgets.QComboBox(self.frame)
        self.cBoxSimbolosPila4.setGeometry(QtCore.QRect(600, 190, 101, 21))
        self.cBoxSimbolosPila4.setObjectName("cBoxSimbolosPila4")
        self.alfabeto2Lbl_4 = QtWidgets.QLabel(self.frame)
        self.alfabeto2Lbl_4.setGeometry(QtCore.QRect(640, 160, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.alfabeto2Lbl_4.setFont(font)
        self.alfabeto2Lbl_4.setObjectName("alfabeto2Lbl_4")
        self.cBoxSimboloIniP4 = QtWidgets.QComboBox(self.frame)
        self.cBoxSimboloIniP4.setGeometry(QtCore.QRect(710, 190, 81, 21))
        self.cBoxSimboloIniP4.setObjectName("cBoxSimboloIniP4")
        self.alfabeto2Lbl_5 = QtWidgets.QLabel(self.frame)
        self.alfabeto2Lbl_5.setGeometry(QtCore.QRect(750, 160, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.alfabeto2Lbl_5.setFont(font)
        self.alfabeto2Lbl_5.setObjectName("alfabeto2Lbl_5")
        self.maquinaLbl_2 = QtWidgets.QLabel(self.frame)
        self.maquinaLbl_2.setGeometry(QtCore.QRect(560, 360, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.maquinaLbl_2.setFont(font)
        self.maquinaLbl_2.setObjectName("maquinaLbl_2")
        self.cadena4Txt = QtWidgets.QLineEdit(self.frame)
        self.cadena4Txt.setGeometry(QtCore.QRect(630, 370, 181, 21))
        self.cadena4Txt.setObjectName("cadena4Txt")
        self.analizar4Btn = QtWidgets.QPushButton(self.frame)
        self.analizar4Btn.setGeometry(QtCore.QRect(660, 410, 101, 29))
        self.analizar4Btn.setObjectName("analizar4Btn")
        self.maquinaLbl_3 = QtWidgets.QLabel(self.frame)
        self.maquinaLbl_3.setGeometry(QtCore.QRect(560, 470, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.maquinaLbl_3.setFont(font)
        self.maquinaLbl_3.setObjectName("maquinaLbl_3")
        self.estActual4Txt = QtWidgets.QLineEdit(self.frame)
        self.estActual4Txt.setGeometry(QtCore.QRect(690, 480, 81, 21))
        self.estActual4Txt.setObjectName("estActual4Txt")
        self.guardarAut4Btn = QtWidgets.QPushButton(self.frame)
        self.guardarAut4Btn.setGeometry(QtCore.QRect(560, 290, 131, 29))
        self.guardarAut4Btn.setObjectName("guardarAut4Btn")
        self.limpiar4Btn = QtWidgets.QPushButton(self.frame)
        self.limpiar4Btn.setGeometry(QtCore.QRect(710, 290, 101, 29))
        self.limpiar4Btn.setObjectName("limpiar4Btn")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(9, 259, 541, 341))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 539, 339))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_6)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(-1, 0, 541, 341))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_6)
        self.sigpaso4Btn = QtWidgets.QPushButton(self.frame)
        self.sigpaso4Btn.setGeometry(QtCore.QRect(640, 540, 111, 29))
        self.sigpaso4Btn.setObjectName("sigpaso4Btn")
        self.alfabeto2Lbl_6 = QtWidgets.QLabel(self.frame)
        self.alfabeto2Lbl_6.setGeometry(QtCore.QRect(790, 180, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.alfabeto2Lbl_6.setFont(font)
        self.alfabeto2Lbl_6.setObjectName("alfabeto2Lbl_6")
        self.maquinaLbl_4 = QtWidgets.QLabel(self.frame)
        self.maquinaLbl_4.setGeometry(QtCore.QRect(0, 220, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.maquinaLbl_4.setFont(font)
        self.maquinaLbl_4.setObjectName("maquinaLbl_4")
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.pestanas.addTab(self.maneraFTab, "")
        self.tablaTab = QtWidgets.QWidget()
        self.tablaTab.setObjectName("tablaTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tablaTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.guardar_gram5Btn = QtWidgets.QPushButton(self.tablaTab)
        self.guardar_gram5Btn.setObjectName("guardar_gram5Btn")
        self.gridLayout_5.addWidget(self.guardar_gram5Btn, 7, 2, 1, 1)
        self.chomsky5Btn = QtWidgets.QPushButton(self.tablaTab)
        self.chomsky5Btn.setObjectName("chomsky5Btn")
        self.gridLayout_5.addWidget(self.chomsky5Btn, 6, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tablaTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 6, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tablaTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 2, 10, 1, 1)
        self.cBoxProducc5 = QtWidgets.QComboBox(self.tablaTab)
        self.cBoxProducc5.setObjectName("cBoxProducc5")
        self.gridLayout_5.addWidget(self.cBoxProducc5, 2, 9, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tablaTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tablaTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 2, 1, 1, 1)
        self.terminales5Txt = QtWidgets.QLineEdit(self.tablaTab)
        self.terminales5Txt.setObjectName("terminales5Txt")
        self.gridLayout_5.addWidget(self.terminales5Txt, 2, 2, 1, 1)
        self.greibach5Btn = QtWidgets.QPushButton(self.tablaTab)
        self.greibach5Btn.setObjectName("greibach5Btn")
        self.gridLayout_5.addWidget(self.greibach5Btn, 6, 1, 1, 1)
        self.limpiar5Btn = QtWidgets.QPushButton(self.tablaTab)
        self.limpiar5Btn.setObjectName("limpiar5Btn")
        self.gridLayout_5.addWidget(self.limpiar5Btn, 7, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tablaTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 0, 8, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tablaTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 2, 4, 1, 1)
        self.variables5Txt = QtWidgets.QLineEdit(self.tablaTab)
        self.variables5Txt.setObjectName("variables5Txt")
        self.gridLayout_5.addWidget(self.variables5Txt, 0, 2, 1, 1)
        self.ok5_2Btn = QtWidgets.QPushButton(self.tablaTab)
        self.ok5_2Btn.setObjectName("ok5_2Btn")
        self.gridLayout_5.addWidget(self.ok5_2Btn, 0, 11, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tablaTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 0, 4, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tablaTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 7, 0, 1, 1)
        self.sInicial5Txt = QtWidgets.QLineEdit(self.tablaTab)
        self.sInicial5Txt.setObjectName("sInicial5Txt")
        self.gridLayout_5.addWidget(self.sInicial5Txt, 0, 9, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tablaTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 2, 8, 1, 1)
        self.ok5_3Btn = QtWidgets.QPushButton(self.tablaTab)
        self.ok5_3Btn.setObjectName("ok5_3Btn")
        self.gridLayout_5.addWidget(self.ok5_3Btn, 2, 5, 1, 1)
        self.ok5_1Btn = QtWidgets.QPushButton(self.tablaTab)
        self.ok5_1Btn.setObjectName("ok5_1Btn")
        self.gridLayout_5.addWidget(self.ok5_1Btn, 0, 5, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tablaTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 0, 1, 1, 1)
        self.agregarProd5Btn = QtWidgets.QPushButton(self.tablaTab)
        self.agregarProd5Btn.setObjectName("agregarProd5Btn")
        self.gridLayout_5.addWidget(self.agregarProd5Btn, 2, 11, 1, 1)
        self.pestanas.addTab(self.tablaTab, "")
        self.arbolRecoTab = QtWidgets.QWidget()
        self.arbolRecoTab.setObjectName("arbolRecoTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.arbolRecoTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.arbolRecoTab)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 815, 605))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_4)
        self.graphicsView_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout.addWidget(self.graphicsView_2)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_7.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.pestanas.addTab(self.arbolRecoTab, "")
        self.gridLayout.addWidget(self.pestanas, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 23))
        self.menubar.setObjectName("menubar")
        self.menuPrincipal = QtWidgets.QMenu(self.menubar)
        self.menuPrincipal.setObjectName("menuPrincipal")
        self.menuOperaciones = QtWidgets.QMenu(self.menuPrincipal)
        self.menuOperaciones.setObjectName("menuOperaciones")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionAutomatas_Cargar = QtWidgets.QAction(MainWindow)
        self.actionAutomatas_Cargar.setObjectName("actionAutomatas_Cargar")
        self.actionLectura = QtWidgets.QAction(MainWindow)
        self.actionLectura.setObjectName("actionLectura")
        self.actionMinimizacion = QtWidgets.QAction(MainWindow)
        self.actionMinimizacion.setObjectName("actionMinimizacion")
        self.actionComplemento = QtWidgets.QAction(MainWindow)
        self.actionComplemento.setObjectName("actionComplemento")
        self.actionUnion = QtWidgets.QAction(MainWindow)
        self.actionUnion.setObjectName("actionUnion")
        self.actionInterseccion = QtWidgets.QAction(MainWindow)
        self.actionInterseccion.setObjectName("actionInterseccion")
        self.actionReversa = QtWidgets.QAction(MainWindow)
        self.actionReversa.setObjectName("actionReversa")
        self.actionConcatenacion = QtWidgets.QAction(MainWindow)
        self.actionConcatenacion.setObjectName("actionConcatenacion")
        self.actionCierre_de_Kleene = QtWidgets.QAction(MainWindow)
        self.actionCierre_de_Kleene.setObjectName("actionCierre_de_Kleene")
        self.actionAFN_a_AFD = QtWidgets.QAction(MainWindow)
        self.actionAFN_a_AFD.setObjectName("actionAFN_a_AFD")
        self.actionCrear_Expresion_Regular = QtWidgets.QAction(MainWindow)
        self.actionCrear_Expresion_Regular.setObjectName("actionCrear_Expresion_Regular")
        self.actionMaquina_Expresion = QtWidgets.QAction(MainWindow)
        self.actionMaquina_Expresion.setObjectName("actionMaquina_Expresion")
        self.menuOperaciones.addAction(self.actionMinimizacion)
        self.menuOperaciones.addAction(self.actionComplemento)
        self.menuOperaciones.addAction(self.actionUnion)
        self.menuOperaciones.addAction(self.actionInterseccion)
        self.menuOperaciones.addAction(self.actionReversa)
        self.menuOperaciones.addAction(self.actionConcatenacion)
        self.menuOperaciones.addAction(self.actionCierre_de_Kleene)
        self.menuOperaciones.addAction(self.actionAFN_a_AFD)
        self.menuOperaciones.addAction(self.actionCrear_Expresion_Regular)
        self.menuOperaciones.addAction(self.actionMaquina_Expresion)
        self.menuPrincipal.addAction(self.actionGuardar)
        self.menuPrincipal.addAction(self.actionAutomatas_Cargar)
        self.menuPrincipal.addAction(self.actionLectura)
        self.menuPrincipal.addAction(self.menuOperaciones.menuAction())
        self.menubar.addAction(self.menuPrincipal.menuAction())

        self.retranslateUi(MainWindow)
        self.pestanas.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "Expresión Regular:"))
        self.ok1Btn.setText(_translate("MainWindow", "O.K"))
        self.pestanas.setTabText(self.pestanas.indexOf(self.tab_2), _translate("MainWindow", "Page"))
        self.estInicialLbl.setText(_translate("MainWindow", "Estado Inicial:"))
        self.alfabetoLbl.setText(_translate("MainWindow", "Alfabeto Σ: "))
        self.label_8.setText(_translate("MainWindow", "Autómata:"))
        self.label_4.setText(_translate("MainWindow", "V = {"))
        self.checkBoxDerecha2.setText(_translate("MainWindow", "Por derecha"))
        self.label_7.setText(_translate("MainWindow", "P = {"))
        self.label_5.setText(_translate("MainWindow", "T= {"))
        self.aplicar2Btn.setText(_translate("MainWindow", "Aplicar"))
        self.estAceptadoresLbl.setText(_translate("MainWindow", "Estados aceptadores: "))
        self.label.setText(_translate("MainWindow", "Transiciones:"))
        self.origenLbl.setText(_translate("MainWindow", "Origen:"))
        self.destinoLbl.setText(_translate("MainWindow", "Destino:"))
        self.label_23.setText(_translate("MainWindow", "}"))
        self.guardarAut2.setText(_translate("MainWindow", "Guardar Autómata"))
        self.valorLbl.setText(_translate("MainWindow", "Valor:"))
        self.aplicarTransiBtn.setText(_translate("MainWindow", "Aplicar Transición"))
        self.guardar_gram2.setText(_translate("MainWindow", "Guardar Gramática"))
        self.checkBoxIzquierda2.setText(_translate("MainWindow", "Por izquierda"))
        self.label_2.setText(_translate("MainWindow", "                                                                   GRAMÁTICA"))
        self.label_24.setText(_translate("MainWindow", "}"))
        self.label_6.setText(_translate("MainWindow", "S ="))
        self.label_22.setText(_translate("MainWindow", "}"))
        self.limpiar2_1Btn.setText(_translate("MainWindow", "Limpiar (Autómata)"))
        self.limpiar2_2Btn.setText(_translate("MainWindow", "Limpiar (Gramática)"))
        self.pestanas.setTabText(self.pestanas.indexOf(self.diagramaTab), _translate("MainWindow", "Tab 1"))
        self.label_15.setText(_translate("MainWindow", "}"))
        self.guardar_gram3Btn.setText(_translate("MainWindow", "Guardar Grámatica"))
        self.ok3_1Btn.setText(_translate("MainWindow", "OK"))
        self.label_13.setText(_translate("MainWindow", "V = {"))
        self.label_12.setText(_translate("MainWindow", "Gramática:"))
        self.label_14.setText(_translate("MainWindow", "S="))
        self.ok3_3Btn.setText(_translate("MainWindow", "OK"))
        self.ok3_2Btn.setText(_translate("MainWindow", "OK"))
        self.label_16.setText(_translate("MainWindow", "T = {"))
        self.label_17.setText(_translate("MainWindow", "}"))
        self.label_18.setText(_translate("MainWindow", "P = {"))
        self.agregarProd3Btn.setText(_translate("MainWindow", "Agregar producción"))
        self.label_19.setText(_translate("MainWindow", "}"))
        self.label_20.setText(_translate("MainWindow", "Cadena:"))
        self.checkBoxDerecha3.setText(_translate("MainWindow", "Por derecha"))
        self.generar3Btn.setText(_translate("MainWindow", "Generar"))
        self.checkBoxIzquierda3.setText(_translate("MainWindow", "Por izquierda"))
        self.label_21.setText(_translate("MainWindow", "Árbol de Derivación:"))
        self.limpiar3_1Btn.setText(_translate("MainWindow", "Limpiar(Gramática)"))
        self.limpiar3_2Btn.setText(_translate("MainWindow", "Limpiar(Árbol)"))
        self.pestanas.setTabText(self.pestanas.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.maquinaLbl.setText(_translate("MainWindow", "M =  {"))
        self.label_3.setText(_translate("MainWindow", "}"))
        self.QLbl.setText(_translate("MainWindow", "Q"))
        self.inicial2Lbl.setText(_translate("MainWindow", "q0"))
        self.aceptadores2Lbl.setText(_translate("MainWindow", "F"))
        self.alfabeto2Lbl.setText(_translate("MainWindow", "Σ"))
        self.transiLbl.setText(_translate("MainWindow", "δ"))
        self.checkBoxInicial4.setText(_translate("MainWindow", "Inicial"))
        self.checkBoxAceptador4.setText(_translate("MainWindow", "Aceptador"))
        self.anadirEstado4Btn.setText(_translate("MainWindow", "Añadir Estado"))
        self.origenLbl_2.setText(_translate("MainWindow", "Origen"))
        self.transi4Btn.setText(_translate("MainWindow", "Añadir Transición"))
        self.alfabeto2Lbl_2.setText(_translate("MainWindow", "Σ = {"))
        self.label_9.setText(_translate("MainWindow", "}"))
        self.alfabeto2Lbl_3.setText(_translate("MainWindow", "T= {"))
        self.label_10.setText(_translate("MainWindow", "}"))
        self.agregarAlfabeto4.setText(_translate("MainWindow", "Agregar alfabeto"))
        self.agregarAPila4.setText(_translate("MainWindow", "Agregar alfabeto(pila)"))
        self.origenLbl_3.setText(_translate("MainWindow", "VALOR"))
        self.origenLbl_4.setText(_translate("MainWindow", "Simbolo entrada"))
        self.origenLbl_5.setText(_translate("MainWindow", "Simbolo pila"))
        self.origenLbl_6.setText(_translate("MainWindow", "Destino"))
        self.origenLbl_7.setText(_translate("MainWindow", "Simbolo escribir en pila"))
        self.alfabeto2Lbl_4.setText(_translate("MainWindow", "T"))
        self.alfabeto2Lbl_5.setText(_translate("MainWindow", "Z0"))
        self.maquinaLbl_2.setText(_translate("MainWindow", "Cadena:"))
        self.analizar4Btn.setText(_translate("MainWindow", "Analizar"))
        self.maquinaLbl_3.setText(_translate("MainWindow", "Estado Actual:"))
        self.guardarAut4Btn.setText(_translate("MainWindow", "Guardar Autómata"))
        self.limpiar4Btn.setText(_translate("MainWindow", "Limpiar"))
        self.sigpaso4Btn.setText(_translate("MainWindow", "Siguiente paso"))
        self.alfabeto2Lbl_6.setText(_translate("MainWindow", "}"))
        self.maquinaLbl_4.setText(_translate("MainWindow", "Pila:"))
        self.pestanas.setTabText(self.pestanas.indexOf(self.maneraFTab), _translate("MainWindow", "Page"))
        self.guardar_gram5Btn.setText(_translate("MainWindow", "Guardar Gramática"))
        self.chomsky5Btn.setText(_translate("MainWindow", "Chomsky"))
        self.label_33.setText(_translate("MainWindow", "Formas Normales:"))
        self.label_32.setText(_translate("MainWindow", "}"))
        self.label_25.setText(_translate("MainWindow", "Gramática:"))
        self.label_29.setText(_translate("MainWindow", "T = {"))
        self.greibach5Btn.setText(_translate("MainWindow", "Greibach"))
        self.limpiar5Btn.setText(_translate("MainWindow", "Limpiar"))
        self.label_27.setText(_translate("MainWindow", "S ="))
        self.label_31.setText(_translate("MainWindow", "}"))
        self.ok5_2Btn.setText(_translate("MainWindow", "OK"))
        self.label_28.setText(_translate("MainWindow", "}"))
        self.label_34.setText(_translate("MainWindow", "Acciones:"))
        self.label_30.setText(_translate("MainWindow", "P = {"))
        self.ok5_3Btn.setText(_translate("MainWindow", "OK"))
        self.ok5_1Btn.setText(_translate("MainWindow", "OK"))
        self.label_26.setText(_translate("MainWindow", "V = {"))
        self.agregarProd5Btn.setText(_translate("MainWindow", "Agregar Producción"))
        self.pestanas.setTabText(self.pestanas.indexOf(self.tablaTab), _translate("MainWindow", "Tab 2"))
        self.pestanas.setTabText(self.pestanas.indexOf(self.arbolRecoTab), _translate("MainWindow", "Page"))
        self.menuPrincipal.setTitle(_translate("MainWindow", "Menu"))
        self.menuOperaciones.setTitle(_translate("MainWindow", "Operaciones"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionAutomatas_Cargar.setText(_translate("MainWindow", "Automatas (Cargar)"))
        self.actionLectura.setText(_translate("MainWindow", "Lectura"))
        self.actionMinimizacion.setText(_translate("MainWindow", "Minimizacion"))
        self.actionComplemento.setText(_translate("MainWindow", "Complemento"))
        self.actionUnion.setText(_translate("MainWindow", "Union"))
        self.actionInterseccion.setText(_translate("MainWindow", "Interseccion"))
        self.actionReversa.setText(_translate("MainWindow", "Reversa"))
        self.actionConcatenacion.setText(_translate("MainWindow", "Concatenacion"))
        self.actionCierre_de_Kleene.setText(_translate("MainWindow", "Cierre de Kleene"))
        self.actionAFN_a_AFD.setText(_translate("MainWindow", "AFN a AFD"))
        self.actionCrear_Expresion_Regular.setText(_translate("MainWindow", "Crear Expresion Regular"))
        self.actionMaquina_Expresion.setText(_translate("MainWindow", "Crear Maquina - Expresion Regular"))

